sudo: required
services:
        - docker
before_install:
        - docker build -t missthetrain888/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run missthetrain888/react-test npm test -- --coverage

after_success:
        - docker build -t missthetrain888/multi-client ./client
        - docker build -t missthetrain888/multi-nginx ./nginx
        - docker build -t missthetrain888/multi-server ./server
        - docker build -t missthetrain888/multi-worker ./worker

        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

        - docker push  missthetrain888/multi-client
        - docker push  missthetrain888/multi-nginx
        - docker push  missthetrain888/multi-server
        - docker push  missthetrain888/multi-worker
